/**
 * Landing Page Component Tests
 *
 * Maps to BDD user stories US-07 and US-08 in .artifacts/task.md.
 * Validates root layout metadata and landing page rendering.
 */
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import fs from "fs";
import path from "path";
import Home from "./page";

const ROOT = path.resolve(__dirname, "..");

describe("US-07: Root Layout and Metadata", () => {
  it("should export metadata with a proper title in layout.tsx", async () => {
    // Arrange
    const layoutModule = await import("./layout");

    // Act
    const metadata = layoutModule.metadata;

    // Assert
    expect(metadata).toBeDefined();
    expect(metadata.title).toBeDefined();
    expect(metadata.title).not.toBe("Create Next App");
    expect(typeof metadata.title === "string" && metadata.title.length).toBeGreaterThan(0);
  });

  it("should export metadata with a proper description in layout.tsx", async () => {
    // Arrange
    const layoutModule = await import("./layout");

    // Act
    const metadata = layoutModule.metadata;

    // Assert
    expect(metadata).toBeDefined();
    expect(metadata.description).toBeDefined();
    expect(metadata.description).not.toBe("Generated by create next app");
    expect(
      typeof metadata.description === "string" && metadata.description.length
    ).toBeGreaterThan(0);
  });

  it("should include the dark class on <html> in layout.tsx source", () => {
    // Arrange
    const layoutSource = fs.readFileSync(
      path.join(ROOT, "app", "layout.tsx"),
      "utf-8"
    );

    // Act & Assert — US-10: dark mode default
    expect(layoutSource).toContain("dark");
  });
});

describe("US-08: Landing Page Placeholder", () => {
  it("should render the project name", () => {
    // Arrange & Act
    render(<Home />);

    // Assert
    expect(screen.getByText(/project zenith/i)).toBeInTheDocument();
  });

  it("should render a status message confirming the stack is operational", () => {
    // Arrange & Act
    render(<Home />);

    // Assert
    expect(
      screen.getByText(/all systems operational/i)
    ).toBeInTheDocument();
  });

  it("should use a Shadcn Button component", () => {
    // Arrange & Act
    render(<Home />);

    // Assert — Shadcn buttons use data-slot="button"
    const buttons = document.querySelectorAll('[data-slot="button"]');
    expect(buttons.length).toBeGreaterThan(0);
  });

  it("should render the correct company branding", () => {
    // Arrange & Act
    render(<Home />);

    // Assert
    const elements = screen.getAllByText(/TTEC Digital/i);
    expect(elements.length).toBeGreaterThan(0);
  });

  it("should render the new mission statement copy", () => {
    // Arrange & Act
    render(<Home />);

    // Assert
    expect(
      screen.getByText(/Project Zenith demonstrates the future of customer experience through multimodal AI/i)
    ).toBeInTheDocument();
  });
});
